//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountGroup()
        {
            this.AccountGroups1 = new HashSet<AccountGroup>();
        }
    
        public decimal AccountGroupId { get; set; }
        public string AccountGroupCode { get; set; }
        public string GroupName { get; set; }
        public string GroupCode { get; set; }
        public Nullable<decimal> Under { get; set; }
        public Nullable<decimal> ProfitAndLoss { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountGroup> AccountGroups1 { get; set; }
        public virtual AccountGroup AccountGroup1 { get; set; }
    }
}
