//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoGeneration
    {
        public decimal AGNID { get; set; }
        public string AGNCode { get; set; }
        public string TableName { get; set; }
        public string prefix { get; set; }
        public Nullable<decimal> KeySize { get; set; }
        public Nullable<decimal> StartFrom { get; set; }
    }
}
