//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank
    {
        public decimal BankId { get; set; }
        public string BankCode { get; set; }
        public string LedgerName { get; set; }
        public string BankName { get; set; }
        public string AcType { get; set; }
        public string MCRCode { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string CPerson1 { get; set; }
        public string MobileNo { get; set; }
        public string CPerson2 { get; set; }
        public string MobileNo2 { get; set; }
    }
}
