//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public decimal CompanyId { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Pincode { get; set; }
        public string PhNo { get; set; }
        public string MobileNo { get; set; }
        public string Tin { get; set; }
        public string Cst { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<double> MinAmount { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
