//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public decimal JDId { get; set; }
        public string JDCode { get; set; }
        public string JournalCode { get; set; }
        public string LedgerCode { get; set; }
        public Nullable<double> DrAmt { get; set; }
        public Nullable<double> CrAmt { get; set; }
        public string Narration { get; set; }
    }
}
