//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalMaster
    {
        public decimal JournalId { get; set; }
        public string JournalCode { get; set; }
        public string EntryNo { get; set; }
        public Nullable<System.DateTime> JournalDate { get; set; }
    }
}
