//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerReport
    {
        public decimal LReportId { get; set; }
        public string LReportCode { get; set; }
        public string VoucherNo { get; set; }
        public string VoucherType { get; set; }
        public Nullable<System.DateTime> LDate { get; set; }
        public string LedgerCode { get; set; }
        public string Particulars { get; set; }
        public string Narration { get; set; }
        public Nullable<double> DRAmount { get; set; }
        public Nullable<double> CRAmount { get; set; }
        public string FU1 { get; set; }
        public string FU2 { get; set; }
        public string FU3 { get; set; }
    }
}
