//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public decimal PaymentId { get; set; }
        public string PaymentCode { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentTo { get; set; }
        public Nullable<decimal> LedgerCodeTo { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> LedgerCodeFrom { get; set; }
        public Nullable<double> PayAmount { get; set; }
        public string Narration { get; set; }
        public string RefNo { get; set; }
        public string Status { get; set; }
        public Nullable<double> ExtraCharge { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        public virtual Ledger Ledger1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
