//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMaster
    {
        public decimal PaymentId { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PurchaseId { get; set; }
        public Nullable<decimal> SupplierId { get; set; }
        public Nullable<decimal> SalesRId { get; set; }
        public Nullable<decimal> CustomerId { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public string Description { get; set; }
    }
}
