//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseMaster
    {
        public int Id { get; set; }
        public string PurchaseCode { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> LedgerCode { get; set; }
        public string PurchaseType { get; set; }
        public Nullable<decimal> InvoiceNo { get; set; }
        public Nullable<decimal> Extra { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string Narration { get; set; }
        public Nullable<double> ItemAmount { get; set; }
        public Nullable<decimal> NoOfProducts { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
