//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptMaster
    {
        public decimal ReceiptId { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<decimal> PurchaseRId { get; set; }
        public Nullable<decimal> SupplierId { get; set; }
        public Nullable<decimal> SalesId { get; set; }
        public Nullable<decimal> CustomerId { get; set; }
        public string ReceiptMode { get; set; }
        public Nullable<decimal> ReceiptAmount { get; set; }
        public string Description { get; set; }
    }
}
