//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public decimal ReceiptId { get; set; }
        public string ReceiptCode { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string ReceiptFrom { get; set; }
        public Nullable<decimal> LedgerCodeFrom { get; set; }
        public string ReceiptMode { get; set; }
        public Nullable<decimal> ReceiptTo { get; set; }
        public Nullable<double> ReceiptAmount { get; set; }
        public string Narration { get; set; }
        public string RefNo { get; set; }
        public string Status { get; set; }
        public Nullable<double> ExtraCharge { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
    
        public virtual Ledger Ledger { get; set; }
        public virtual Ledger Ledger1 { get; set; }
    }
}
