//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public decimal RDId { get; set; }
        public string RDCode { get; set; }
        public string ReceiptCode { get; set; }
        public string RefCode { get; set; }
        public string RefType { get; set; }
        public Nullable<double> Amount { get; set; }
    }
}
