//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReturnDetail
    {
        public decimal SRDId { get; set; }
        public string SRDCode { get; set; }
        public Nullable<decimal> SRId { get; set; }
        public string SalesCode { get; set; }
        public Nullable<decimal> ProductCode { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> UOM { get; set; }
        public string TaxPer { get; set; }
        public Nullable<double> DisPer { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SalesReturn SalesReturn { get; set; }
        public virtual UnitsOfMeasurement UnitsOfMeasurement { get; set; }
    }
}
