//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public decimal StaffId { get; set; }
        public string StaffCode { get; set; }
        public string LedgerName { get; set; }
        public string StaffName { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public string ContactNum { get; set; }
        public string MailId { get; set; }
    }
}
