//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxMaster
    {
        public decimal TaxId { get; set; }
        public string TaxCode { get; set; }
        public Nullable<double> TaxValue { get; set; }
        public string Narration { get; set; }
    }
}
