//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TextTranslation
    {
        public decimal TTId { get; set; }
        public string TTCode { get; set; }
        public string TTEnglish { get; set; }
        public string TTTamil { get; set; }
    }
}
