//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JJSuperMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpProduct
    {
        public int Sno { get; set; }
        public Nullable<int> BarCode { get; set; }
        public string Product { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<int> Qty { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
    }
}
